import assert from 'node:assert/strict'
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright')
const browser = await chromium.launch({ headless: true, executablePath: process.env.CHROMIUM_EXECUTABLE })
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' })
const errors = []
page.on('pageerror', error => errors.push(error.message))
await page.goto(process.env.TEST_URL || 'http://localhost:4173', { waitUntil: 'networkidle' })
await page.locator('ds-alert').first().waitFor()
const mixed = page.locator('ds-checkbox input').nth(2)
assert.equal(await mixed.evaluate(el => el.indeterminate), true)
await mixed.focus(); await page.keyboard.press('Space')
assert.equal(await mixed.evaluate(el => el.indeterminate), false)
const firstTab = page.locator('#demo-overview-tab')
await firstTab.focus(); await page.keyboard.press('ArrowRight')
assert.equal(await page.evaluate(() => document.activeElement.id), 'demo-activity-tab')
await page.keyboard.press('Enter')
await page.waitForFunction(() => document.querySelector('#demo-activity-tab').getAttribute('aria-selected') === 'true')
assert.equal(await page.locator('#demo-activity-tab').getAttribute('aria-selected'), 'true')
assert.equal(await page.locator('#demo-activity-panel').isVisible(), true)
await page.getByRole('button', { name: 'Dismiss notification' }).click()
await page.locator('ds-alert[severity="warning"]').waitFor({ state: 'detached' })
assert.equal(await page.locator('ds-alert[severity="warning"]').count(), 0)
assert.equal(await page.evaluate(() => document.activeElement.textContent.trim()), 'Restore warning example')
await page.getByRole('button', { name: 'Restore warning example' }).click()
await page.getByRole('button', { name: 'Review status', exact: true }).click()
await page.waitForFunction(() => document.querySelector('p[role="status"]').textContent.includes('Status review requested.'))
assert.equal(await page.locator('p[role="status"]').textContent(), 'Status review requested.')
const tip = page.locator('ds-tooltip').first(), trigger = tip.locator('button')
await trigger.focus()
assert.match(await trigger.getAttribute('aria-describedby'), /ds-tooltip-/)
await page.keyboard.press('Escape')
await page.waitForFunction(() => document.querySelector('ds-tooltip').classList.contains('ds-tooltip--dismissed'))
assert.equal(await tip.locator('[role="tooltip"]').evaluate(el => getComputedStyle(el).visibility), 'hidden')
const toolbar = page.locator('ds-toolbar').first()
const controls = toolbar.locator('button:not(:disabled)')
await controls.first().focus(); await page.keyboard.press('ArrowRight')
assert.equal(await controls.nth(1).evaluate(el => el === document.activeElement), true)
assert.equal(await toolbar.locator('button[tabindex="0"]').count(), 1)
assert.equal(await page.locator('ds-search-bar, ds-search-panel').count(), 0)
const dropdown = page.locator('ds-dropdown').first()
await dropdown.getByRole('combobox').click()
assert.equal(await dropdown.getByRole('listbox').isVisible(), true)
await dropdown.getByRole('combobox').press('ArrowDown')
await dropdown.getByRole('combobox').press('Enter')
await page.waitForFunction(() => document.querySelector('ds-dropdown button').textContent.includes('Engineering'))
await dropdown.getByRole('combobox').click()
await dropdown.getByRole('option', { name: 'Archived (unavailable)' }).click({ force: true })
assert.equal(await dropdown.getByRole('listbox').isVisible(), true)
await dropdown.getByRole('combobox').press('Escape')
assert.equal(await dropdown.getByRole('listbox').isVisible(), false)
await dropdown.getByRole('combobox').click()
await page.mouse.click(5,5)
await page.waitForFunction(() => document.querySelector('ds-dropdown button').getAttribute('aria-expanded') === 'false')
await page.locator('#components').scrollIntoViewIfNeeded()
await page.screenshot({ path: 'output/accessibility-desktop.png' })
await page.setViewportSize({ width: 390, height: 844 })
await dropdown.getByRole('combobox').click()
await page.screenshot({ path: 'output/dropdown-mobile.png' })
await page.keyboard.press('Escape')
await page.locator('ds-alert').first().scrollIntoViewIfNeeded()
for (const alert of await page.locator('ds-alert').all()) {
 const box = await alert.boundingBox(); assert.ok(box.width <= 390)
}
await page.screenshot({ path: 'output/accessibility-mobile.png' })
await page.getByRole('button', { name: 'Switch to dark mode' }).click()
await page.locator('ds-alert').first().scrollIntoViewIfNeeded()
await page.screenshot({ path: 'output/accessibility-dark.png' })
assert.deepEqual(errors, [])
console.log('PASS: dropdown keyboard selection/disabled/light dismissal; Search removal; mixed checkbox; tabs; alert action/dismiss/focus; tooltip Escape; toolbar; responsive alert layout; no browser errors.')
await browser.close()
